### PR TITLE
Rebase @yohanboniface changes.

### PR DESCRIPTION
**Pull request by Natim**
Revamp of #73.

### CODE REVIEW

**Comment by willkg** [comment]
@Natim Is this ready to go? Are you waiting for a review from someone?

**Comment by EnTeQuAk** [comment]
Looks great for me too, I just tried it and couldn't see any obvious problems. Let's merge this :)

**Comment by Natim** [comment]
Thanks @EnTeQuAk for trying. @willkg we are good to go thanks a lot.

**Comment by willkg** [comment]
Awesome--merging!

**Pull request merged**
